### ISSUE TITLE
Typo in Github About description

### ISSUE THREAD

**Issue by agsdot** [lestrrat-go/backoff#14]
@lestrrat , there is a typo in the Github about description. One cannot do a PR against that. 

Creating and sending a screenshot so that you are aware of it. 

![Screen Shot 2020-08-26 at 9 59 24 AM](https://user-images.githubusercontent.com/1510449/91333885-0cd15980-e783-11ea-967b-fe85d6bd3540.png)

algorigthms -> algorithms

**Comment by lestrrat** [comment]
Thank you!

**Comment by agsdot** [comment]
You're welcome. No problem @lestrrat.
