### ISSUE TITLE
v2: it seems some options don't work in exponential backoff policy

### ISSUE THREAD

**Issue by moznion** [lestrrat-go/backoff#19]
Hello,

It seems `WithJitterFactor()`, `WithMaxInterval()`, `WithMinInterval()`, `WithMultiplier()`, and `WithRNG()` aren't active in exponential backoff policy.

The factory of exponential policy is here
https://github.com/lestrrat-go/backoff/blob/1d29930f9d45170070e73ee7d136fcc0bc397f29/v2/backoff.go#L14

and, it goes here
https://github.com/lestrrat-go/backoff/blob/1d29930f9d45170070e73ee7d136fcc0bc397f29/v2/exponential.go#L104

then, it appends a parameter into `igOptions` if the parameter is `identInterval{}`
https://github.com/lestrrat-go/backoff/blob/1d29930f9d45170070e73ee7d136fcc0bc397f29/v2/exponential.go#L110-L111

after it starts the policy, it calls `NewExponentialInterval(p.igOptions...)`
https://github.com/lestrrat-go/backoff/blob/1d29930f9d45170070e73ee7d136fcc0bc397f29/v2/exponential.go#L124

it seems `NewExponentialInterval()` accepts various options, but `igOptions` contains only `identInterval{}`, as mentioned at the above, so most options hasn't been active.
https://github.com/lestrrat-go/backoff/blob/1d29930f9d45170070e73ee7d136fcc0bc397f29/v2/exponential.go#L32-L43

Is this expected behavior?

**Comment by lestrrat** [comment]
Wow. How did I miss that.

**Comment by lestrrat** [comment]
@moznion Please check #20

**Comment by moznion** [comment]
@lestrrat Looks good to me. I appreciate your quick fix 🙏

**Comment by lestrrat** [comment]
Let me know when you are done incorporating `backoff` into your work (i.e. no more glaringly obvious bugs) and I'll make a release
