### ISSUE TITLE
Last Commit no Go files in

### ISSUE THREAD

**Issue by ellertal** [lestrrat-go/backoff#27]
I cant build my proyect, fail the `go get` because i use some library to use this proyect. Im find  the last commit not pass the test, fail.

```
github.com/lestrrat-go/jwx (download)
github.com/pkg/errors (download)
github.com/lestrrat-go/iter (download)
github.com/lestrrat-go/backoff (download)
package github.com/lestrrat-go/backoff/v2: no Go files in /go/src/github.com/lestrrat-go/backoff/v2
```
Thanks!

**Comment by lestrrat** [comment]
you are using go in GOPATH mode, which is being phased out over the past few go releases. please take this as a chance to switch to using go.mod

similar discussion here
https://github.com/lestrrat-go/jwx/issues/315

**Comment by lestrrat** [comment]
what you "should" do is this https://github.com/lestrrat-go/jwx/issues/315#issuecomment-767516640

if you want to punt it, see my comment latet on working around it

**Comment by ellertal** [comment]
Thanks for you comments, I try fix it with your  advice

**Comment by lestrrat** [comment]
I'm going to close this for now, but if you believe this is something that my library should fix, reopen and provide extra details!
