### ISSUE TITLE
Goroutine will leak If parent context has not been canceled 

### ISSUE THREAD

**Issue by johejo** [lestrrat-go/backoff#31]
Reproduction

```go
package main

import (
	"context"
	"fmt"
	"runtime"
	"time"

	"github.com/lestrrat-go/backoff/v2"
)

func main() {
	go func() {
		for {
			fmt.Println(runtime.NumGoroutine())
			time.Sleep(1 * time.Second)
		}
	}()
	go func() {
		for {
			p := backoff.NewExponentialPolicy()
			ctx := context.Background()
			c := p.Start(ctx)
			for backoff.Continue(c) {
				time.Sleep(1 * time.Second)
				break
			}
		}
	}()
	select {}
}
```

```
$ go run ./backoffgoroutineleak.go
4
4
5
6
7
8
9
10
12
12
14
14
15
16
17
...
```

The workaround is to cancel the context.
```go
for {
	p := backoff.NewExponentialPolicy()
	ctx, cancel := context.Background()
	c := p.Start(ctx)
	for backoff.Continue(c) {
		time.Sleep(1 * time.Second)
		break
	}
	cancel()
}
```

This will be difficult to fix inside the letrrat-go/backoff with the current  v2 API design.
The README and example show the code using canceling context, so most users avoid this.
But it's better the documentation clearly mention and warn this goroutine leaks and workarround.

**Comment by lestrrat** [comment]
Yes, I think the documentation can be clearer. But no, I don't think this is something that needs to be "fixed", even if it could have been fixed.

Anyways, I agree the documentation can be a bit more explicit like this:

```
// Start starts a new goroutine that will control the backoff intervals. The caller is
// expected to properly cancel the `context.Context` object that was provided, or
// otherwise the underlying goroutine will leak.
func ...
```

**Comment by lestrrat** [comment]
I'll go ahead an merge #32. Thanks for reporting!

**Comment by johejo** [comment]
The documentation looks good.  Thanks for your quick reaction!
