### ISSUE TITLE
race condition in exponential backoff

### ISSUE THREAD

**Issue by awishformore** [lestrrat-go/backoff#9]
Currently, the exponential backoff uses a random source from the policy, shared between all backoffs. This means that concurrent use of several backoffs from the same policy will lead to a race condition.

From the documentation of the `math/rand` package:

```
The default Source is safe for concurrent use by multiple goroutines, but Sources created by NewSource are not.
```

I proposed a fix in #10

**Comment by lestrrat** [comment]
This had been merged previously, but I forgot to close the issue.
